import time
import os
import json
import platform
import socket

from urllib.request import Request, urlopen
from urllib.error import HTTPError, URLError
from datetime import datetime

from monitor import display_system_status
from process_monitor import get_running_processes, get_process_list
from process_metadata import get_process_details
from network_monitor import get_network_connections
from detector import (
    analyze_processes,
    analyze_process_metadata,
    display_alerts
)
from risk_engine import calculate_risk_score, display_risk_score
from logger import log_event
from database import initialize_database, save_event


# ============================================================
# SENTINELX CLOUD CONFIGURATION
# ============================================================

CLOUD_INGEST_URL = os.environ.get(
    "SENTINELX_CLOUD_URL",
    "https://sentinelx-os1m.onrender.com/api/ingest"
)

CLOUD_INGEST_KEY = os.environ.get(
    "INGEST_API_KEY"
)

CLOUD_SNAPSHOT_URL = os.environ.get(
    "SENTINELX_SNAPSHOT_URL",
    "https://sentinelx-os1m.onrender.com/api/snapshot"
)


# ============================================================
# ALERT SEVERITY PRIORITY
# ============================================================

SEVERITY_PRIORITY = {
    "INFO": 0,
    "LOW": 20,
    "MEDIUM": 50,
    "HIGH": 75,
    "CRITICAL": 100
}


# ============================================================
# PROCESS STATE TRACKING
# ============================================================

# Stores suspicious process identities that were already
# observed during previous monitoring cycles.
#
# Primary identity:
#
#     process_name + PID
#
# If PID information is unavailable, SentinelX falls back
# to process name.
#
# This prevents the same continuously-running process from
# generating a new SECURITY_ALERT every 30 seconds.

PREVIOUS_SUSPICIOUS_PROCESSES = set()


# ============================================================
# ALERT DEDUPLICATION
# ============================================================

def deduplicate_alerts(alerts):
    """
    Remove duplicate alerts generated by different
    detection layers during the same monitoring cycle.

    If the same process is detected multiple times,
    the alert with the highest severity is retained.
    """

    if not alerts:
        return []

    unique_alerts = {}

    for alert in alerts:

        process = str(
            alert.get("process", "")
        ).lower().strip()

        reason = str(
            alert.get("reason", "")
        ).strip()

        severity = str(
            alert.get("severity", "INFO")
        ).upper().strip()

        alert_key = process

        if not alert_key:
            alert_key = reason.lower()

        if alert_key not in unique_alerts:

            unique_alerts[alert_key] = {
                "process": alert.get(
                    "process",
                    "Unknown"
                ),
                "reason": reason,
                "severity": severity
            }

            continue

        existing_alert = unique_alerts[alert_key]

        existing_severity = str(
            existing_alert.get(
                "severity",
                "INFO"
            )
        ).upper()

        existing_score = SEVERITY_PRIORITY.get(
            existing_severity,
            0
        )

        new_score = SEVERITY_PRIORITY.get(
            severity,
            0
        )

        if new_score > existing_score:

            unique_alerts[alert_key] = {
                "process": alert.get(
                    "process",
                    "Unknown"
                ),
                "reason": reason,
                "severity": severity
            }

        elif new_score == existing_score:

            existing_reason = existing_alert.get(
                "reason",
                ""
            )

            if (
                reason
                and reason != existing_reason
                and len(reason) > len(existing_reason)
            ):

                unique_alerts[alert_key] = {
                    "process": alert.get(
                        "process",
                        "Unknown"
                    ),
                    "reason": reason,
                    "severity": severity
                }

    return list(
        unique_alerts.values()
    )


# ============================================================
# PROCESS STATE HELPERS
# ============================================================

def normalize_process_name(process_name):
    """
    Normalize a process name for reliable comparison.
    """

    return str(
        process_name or ""
    ).lower().strip()


def get_process_pid(process):
    """
    Safely extract a PID from a process dictionary.

    Different process-monitoring implementations may use
    different key names, so SentinelX checks common variants.
    """

    possible_keys = [
        "pid",
        "PID",
        "process_id",
        "ProcessId",
        "processId"
    ]

    for key in possible_keys:

        if key in process:

            try:

                return int(
                    process[key]
                )

            except (
                TypeError,
                ValueError
            ):

                return None

    return None


def build_current_process_state(process_list):
    """
    Build a lookup of currently running processes.

    Example:

        {
            "rundll32.exe": [1234],
            "powershell.exe": [4567, 7890]
        }
    """

    current_processes = {}

    for process in process_list:

        if not isinstance(
            process,
            dict
        ):
            continue

        name = normalize_process_name(
            process.get(
                "name",
                ""
            )
        )

        if not name:
            continue

        pid = get_process_pid(
            process
        )

        if name not in current_processes:

            current_processes[name] = []

        if pid is not None:

            current_processes[name].append(
                pid
            )

    return current_processes


def filter_new_process_alerts(
    alerts,
    process_list
):
    """
    Return only alerts belonging to newly observed
    suspicious process executions.

    Existing processes are suppressed from generating
    another SECURITY_ALERT.

    PID is used whenever available.

    Process name is used as a fallback when PID is
    unavailable.

    IMPORTANT:
    This function only controls NEW ALERT GENERATION.

    It does NOT determine the current risk score.
    """

    global PREVIOUS_SUSPICIOUS_PROCESSES

    if not alerts:

        PREVIOUS_SUSPICIOUS_PROCESSES = set()

        return []

    current_processes = build_current_process_state(
        process_list
    )

    current_state = set()

    new_alerts = []

    for alert in alerts:

        process_name = normalize_process_name(
            alert.get(
                "process",
                ""
            )
        )

        if not process_name:

            continue

        pids = current_processes.get(
            process_name,
            []
        )

        # ----------------------------------------------------
        # PID-BASED TRACKING
        # ----------------------------------------------------

        if pids:

            for pid in pids:

                state_key = (
                    process_name,
                    pid
                )

                current_state.add(
                    state_key
                )

                if (
                    state_key
                    not in PREVIOUS_SUSPICIOUS_PROCESSES
                ):

                    new_alert = dict(
                        alert
                    )

                    new_alert["pid"] = pid

                    new_alerts.append(
                        new_alert
                    )

        # ----------------------------------------------------
        # NAME-BASED FALLBACK
        # ----------------------------------------------------

        else:

            state_key = (
                process_name,
                "NAME_ONLY"
            )

            current_state.add(
                state_key
            )

            if (
                state_key
                not in PREVIOUS_SUSPICIOUS_PROCESSES
            ):

                new_alerts.append(
                    dict(alert)
                )

    # Update state for the next monitoring cycle.
    PREVIOUS_SUSPICIOUS_PROCESSES = current_state

    return new_alerts


# ============================================================
# CLOUD EVENT SENDER
# ============================================================

def send_event_to_cloud(
    event_type,
    message,
    severity="INFO",
    process=None,
    risk_score=0,
    timestamp=None
):
    """
    Send a SentinelX event to the Render cloud API.

    Local storage remains independent from cloud storage.
    If cloud ingestion fails, SentinelX continues running.
    """

    if not CLOUD_INGEST_KEY:

        print(
            "Cloud ingestion skipped: "
            "INGEST_API_KEY is not configured."
        )

        return False

    if timestamp is None:

        timestamp = datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )

    event_data = {
        "timestamp": timestamp,
        "event_type": event_type,
        "severity": severity,
        "process": process or "",
        "message": message,
        "risk_score": int(risk_score)
    }

    try:

        request_data = json.dumps(
            event_data
        ).encode("utf-8")

        request = Request(
            CLOUD_INGEST_URL,
            data=request_data,
            headers={
                "Content-Type": "application/json",
                "X-SentinelX-Key": CLOUD_INGEST_KEY
            },
            method="POST"
        )

        with urlopen(
            request,
            timeout=15
        ) as response:

            response.read()

            if response.status in (200, 201):

                print(
                    "Cloud event uploaded successfully."
                )

                return True

            print(
                f"Cloud ingestion returned HTTP "
                f"{response.status}"
            )

            return False

    except HTTPError as error:

        print(
            f"Cloud ingestion HTTP error: "
            f"{error.code} {error.reason}"
        )

        return False

    except URLError as error:

        print(
            f"Cloud ingestion connection error: "
            f"{error.reason}"
        )

        return False

    except Exception as error:

        print(
            f"Cloud ingestion error: {error}"
        )

        return False


# ============================================================
# WINDOWS SYSTEM SNAPSHOT
# ============================================================

def collect_system_snapshot():
    """
    Collect system information from the Windows machine
    running SentinelX.
    """

    try:

        hostname = socket.gethostname()

    except Exception:

        hostname = "Unknown"

    # SentinelX dashboard display name.
    # This does NOT change the actual Windows account.

    username = "Suraj Baliarsingh"

    try:

        operating_system = platform.system()

    except Exception:

        operating_system = "Unknown"

    try:

        os_version = platform.version()

    except Exception:

        os_version = "Unknown"

    return {
        "hostname": hostname,
        "operating_system": operating_system,
        "os_version": os_version,
        "username": username
    }


# ============================================================
# CLOUD SNAPSHOT SENDER
# ============================================================

def send_monitoring_snapshot(
    system_snapshot,
    processes,
    network_connections,
    risk_score
):
    """
    Upload the latest Windows monitoring snapshot.
    """

    if not CLOUD_INGEST_KEY:

        print(
            "Cloud snapshot skipped: "
            "INGEST_API_KEY is not configured."
        )

        return False

    timestamp = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    snapshot_data = {
        "timestamp": timestamp,
        "system": system_snapshot,
        "processes": processes,
        "network": network_connections,
        "risk_score": int(risk_score)
    }

    try:

        request_data = json.dumps(
            snapshot_data
        ).encode("utf-8")

        request = Request(
            CLOUD_SNAPSHOT_URL,
            data=request_data,
            headers={
                "Content-Type": "application/json",
                "X-SentinelX-Key": CLOUD_INGEST_KEY
            },
            method="POST"
        )

        with urlopen(
            request,
            timeout=20
        ) as response:

            response.read()

            if response.status in (200, 201):

                print(
                    "Windows monitoring snapshot "
                    "uploaded successfully."
                )

                return True

            print(
                f"Cloud snapshot returned HTTP "
                f"{response.status}"
            )

            return False

    except HTTPError as error:

        print(
            f"Cloud snapshot HTTP error: "
            f"{error.code} {error.reason}"
        )

        return False

    except URLError as error:

        print(
            f"Cloud snapshot connection error: "
            f"{error.reason}"
        )

        return False

    except Exception as error:

        print(
            f"Cloud snapshot error: {error}"
        )

        return False


# ============================================================
# SAVE LOCAL + CLOUD EVENT
# ============================================================

def save_and_sync_event(
    event_type,
    message,
    severity="INFO",
    process=None,
    risk_score=0
):
    """
    Save an event locally and then attempt cloud ingestion.

    Local storage is never dependent on cloud availability.
    """

    timestamp = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    local_saved = save_event(
        event_type=event_type,
        message=message,
        severity=severity,
        process=process,
        risk_score=risk_score,
        timestamp=timestamp
    )

    cloud_saved = send_event_to_cloud(
        event_type=event_type,
        message=message,
        severity=severity,
        process=process,
        risk_score=risk_score,
        timestamp=timestamp
    )

    return local_saved, cloud_saved


# ============================================================
# BANNER
# ============================================================

def show_banner():

    print("================================")
    print("          SENTINELX")
    print(" Cybersecurity Monitoring System")
    print("================================")


# ============================================================
# MONITORING CYCLE
# ============================================================

def monitoring_cycle():

    print(
        "\n========== MONITORING CYCLE =========="
    )

    # --------------------------------------------
    # START MONITORING CYCLE
    # --------------------------------------------

    log_event(
        "SYSTEM",
        "Monitoring cycle started",
        "INFO"
    )

    # --------------------------------------------
    # SYSTEM STATUS
    # --------------------------------------------

    display_system_status()

    system_snapshot = collect_system_snapshot()

    # --------------------------------------------
    # PROCESS MONITORING
    # --------------------------------------------

    print(
        "Collecting running processes..."
    )

    raw_processes = get_running_processes()
    process_list = get_process_list()

    print(
        "Analyzing processes..."
    )

    # --------------------------------------------
    # BASIC PROCESS DETECTION
    # --------------------------------------------

    alerts = analyze_processes(
        raw_processes
    )

    # --------------------------------------------
    # PROCESS METADATA ANALYSIS
    # --------------------------------------------

    metadata_processes = {
        "powershell.exe",
        "wscript.exe",
        "cscript.exe",
        "mshta.exe",
        "regsvr32.exe",
        "rundll32.exe"
    }

    for process in process_list:

        process_name = normalize_process_name(
            process.get(
                "name",
                ""
            )
        )

        if process_name in metadata_processes:

            try:

                metadata = get_process_details(
                    process["pid"]
                )

                metadata_alerts = (
                    analyze_process_metadata(
                        metadata
                    )
                )

                alerts.extend(
                    metadata_alerts
                )

            except Exception as error:

                pid = process.get(
                    "pid",
                    "Unknown"
                )

                print(
                    f"Metadata analysis failed for "
                    f"{process_name} "
                    f"(PID {pid}): "
                    f"{error}"
                )

                log_event(
                    "SYSTEM",
                    (
                        f"Metadata analysis failed for "
                        f"{process_name} "
                        f"(PID {pid})"
                    ),
                    "INFO"
                )

    # --------------------------------------------
    # DUPLICATE ALERT CORRELATION
    # --------------------------------------------

    original_alert_count = len(
        alerts
    )

    alerts = deduplicate_alerts(
        alerts
    )

    deduplicated_alert_count = len(
        alerts
    )

    removed_alert_count = (
        original_alert_count
        - deduplicated_alert_count
    )

    if removed_alert_count > 0:

        print(
            f"Alert correlation removed "
            f"{removed_alert_count} "
            f"duplicate detection(s)."
        )

        log_event(
            "SYSTEM",
            (
                f"Alert correlation removed "
                f"{removed_alert_count} "
                f"duplicate detection(s)"
            ),
            "INFO"
        )

    # ========================================================
    # IMPORTANT:
    #
    # Keep ALL currently active alerts separately.
    #
    # These are used for CURRENT RISK.
    #
    # Only NEW alerts are used for SECURITY_ALERT events.
    # ========================================================

    active_alerts = list(
        alerts
    )

    # --------------------------------------------
    # NEW PROCESS EXECUTION FILTER
    # --------------------------------------------

    previous_alert_count = len(
        alerts
    )

    new_alerts = filter_new_process_alerts(
        alerts,
        process_list
    )

    suppressed_alert_count = (
        previous_alert_count
        - len(new_alerts)
    )

    if suppressed_alert_count > 0:

        print(
            f"Process-state tracking suppressed "
            f"{suppressed_alert_count} "
            f"already-active alert(s)."
        )

        log_event(
            "SYSTEM",
            (
                f"Process-state tracking suppressed "
                f"{suppressed_alert_count} "
                f"already-active alert(s)"
            ),
            "INFO"
        )

    # --------------------------------------------
    # SECURITY ANALYSIS DISPLAY
    # --------------------------------------------

    if new_alerts:

        display_alerts(
            new_alerts
        )

    else:

        print(
            "No new suspicious process executions detected."
        )

    # --------------------------------------------
    # SAVE NEW SECURITY ALERTS ONLY
    # --------------------------------------------

    for alert in new_alerts:

        message = (
            f"{alert['process']} - "
            f"{alert['reason']}"
        )

        pid = alert.get(
            "pid"
        )

        if pid is not None:

            message = (
                f"{message} "
                f"(PID: {pid})"
            )

        log_event(
            "SECURITY_ALERT",
            message,
            alert["severity"]
        )

        alert_risk_score = calculate_risk_score(
            [alert]
        )

        save_and_sync_event(
            event_type="SECURITY_ALERT",
            message=message,
            severity=alert["severity"],
            process=alert["process"],
            risk_score=alert_risk_score
        )

    # ========================================================
    # CURRENT RISK ASSESSMENT
    #
    # IMPORTANT:
    #
    # Risk is calculated from ALL currently active
    # suspicious processes, not only newly generated alerts.
    #
    # Therefore:
    #
    # New rundll32.exe:
    #     SECURITY_ALERT + Risk 20
    #
    # Same rundll32.exe next cycle:
    #     No SECURITY_ALERT + Risk 20
    #
    # rundll32.exe disappears:
    #     No active alert + Risk 0
    # ========================================================

    risk_score = calculate_risk_score(
        active_alerts
    )

    display_risk_score(
        risk_score
    )

    log_event(
        "RISK_ASSESSMENT",
        f"Risk score: {risk_score}/100",
        "INFO"
    )

    save_and_sync_event(
        event_type="RISK_ASSESSMENT",
        message=f"Risk score: {risk_score}/100",
        severity="INFO",
        risk_score=risk_score
    )

    # --------------------------------------------
    # NETWORK MONITORING
    # --------------------------------------------

    print(
        "Collecting network connections..."
    )

    connections = get_network_connections()

    connection_count = len(
        [
            line
            for line in connections.splitlines()
            if line.strip()
        ]
    )

    print(
        f"Network records collected: "
        f"{connection_count}"
    )

    log_event(
        "NETWORK",
        (
            f"{connection_count} "
            f"network records collected"
        ),
        "INFO"
    )

    save_and_sync_event(
        event_type="NETWORK",
        message=(
            f"{connection_count} "
            f"network records collected"
        ),
        severity="INFO",
        risk_score=risk_score
    )

    # --------------------------------------------
    # WINDOWS SNAPSHOT
    # --------------------------------------------

    print(
        "Preparing Windows monitoring snapshot..."
    )

    try:

        snapshot_result = send_monitoring_snapshot(
            system_snapshot=system_snapshot,
            processes=process_list,
            network_connections=connections,
            risk_score=risk_score
        )

        if snapshot_result:

            print(
                "Windows snapshot synchronization: SUCCESS"
            )

        else:

            print(
                "Windows snapshot synchronization: FAILED"
            )

    except Exception as error:

        print(
            f"Windows snapshot synchronization "
            f"error: {error}"
        )

    # --------------------------------------------
    # CYCLE COMPLETE
    # --------------------------------------------

    log_event(
        "SYSTEM",
        "Monitoring cycle completed",
        "INFO"
    )

    print(
        "======================================="
    )


# ============================================================
# MAIN
# ============================================================

def main():

    print(
        "Starting SentinelX...\n"
    )

    show_banner()

    # --------------------------------------------
    # DATABASE INITIALIZATION
    # --------------------------------------------

    initialize_database()

    # --------------------------------------------
    # CLOUD STATUS
    # --------------------------------------------

    if CLOUD_INGEST_KEY:

        print(
            "Cloud ingestion: ENABLED"
        )

        print(
            f"Cloud API: {CLOUD_INGEST_URL}"
        )

        print(
            f"Snapshot API: {CLOUD_SNAPSHOT_URL}"
        )

    else:

        print(
            "Cloud ingestion: DISABLED"
        )

        print(
            "Set INGEST_API_KEY to enable "
            "cloud upload."
        )

    # --------------------------------------------
    # START LOGGING
    # --------------------------------------------

    log_event(
        "SYSTEM",
        "SentinelX continuous monitoring started",
        "INFO"
    )

    # --------------------------------------------
    # CONTINUOUS MONITORING
    # --------------------------------------------

    try:

        while True:

            monitoring_cycle()

            print(
                "\nNext monitoring cycle in "
                "30 seconds..."
            )

            print(
                "Press Ctrl+C to stop SentinelX."
            )

            time.sleep(30)

    except KeyboardInterrupt:

        print(
            "\nSentinelX stopped by user."
        )

        log_event(
            "SYSTEM",
            "SentinelX stopped by user",
            "INFO"
        )

        save_and_sync_event(
            event_type="SYSTEM",
            message="SentinelX stopped by user",
            severity="INFO",
            risk_score=0
        )


# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()