import time
import os
import json
import platform
import socket
import getpass

from urllib.request import Request, urlopen
from urllib.error import HTTPError, URLError
from datetime import datetime

from monitor import display_system_status
from process_monitor import get_running_processes, get_process_list
from process_metadata import get_process_details
from network_monitor import get_network_connections
from detector import (
    analyze_processes,
    analyze_process_metadata,
    display_alerts
)
from risk_engine import calculate_risk_score, display_risk_score
from logger import log_event
from database import initialize_database, save_event


# ============================================================
# SENTINELX CLOUD CONFIGURATION
# ============================================================

CLOUD_INGEST_URL = os.environ.get(
    "SENTINELX_CLOUD_URL",
    "https://sentinelx-os1m.onrender.com/api/ingest"
)

CLOUD_INGEST_KEY = os.environ.get(
    "INGEST_API_KEY"
)

# Windows monitoring snapshot endpoint
CLOUD_SNAPSHOT_URL = os.environ.get(
    "SENTINELX_SNAPSHOT_URL",
    "https://sentinelx-os1m.onrender.com/api/snapshot"
)


# ============================================================
# ALERT SEVERITY PRIORITY
# ============================================================

SEVERITY_PRIORITY = {
    "INFO": 0,
    "LOW": 20,
    "MEDIUM": 50,
    "HIGH": 75,
    "CRITICAL": 100
}


# ============================================================
# ALERT DEDUPLICATION
# ============================================================

def deduplicate_alerts(alerts):
    """
    Remove duplicate alerts generated by different
    detection layers during the same monitoring cycle.

    If the same process is detected multiple times,
    the alert with the highest severity is retained.

    Example:

        Basic detector:
        rundll32.exe -> LOW

        Metadata detector:
        rundll32.exe -> HIGH

    Final result:

        rundll32.exe -> HIGH

    This prevents one real detection from being counted
    as multiple security alerts.
    """

    if not alerts:
        return []

    unique_alerts = {}

    for alert in alerts:

        process = str(
            alert.get("process", "")
        ).lower().strip()

        reason = str(
            alert.get("reason", "")
        ).strip()

        severity = str(
            alert.get("severity", "INFO")
        ).upper().strip()

        # ----------------------------------------------------
        # Use process as the primary correlation key.
        #
        # SentinelX treats multiple detections of the same
        # monitored process as one security alert per cycle.
        # ----------------------------------------------------

        alert_key = process

        # If process name is unavailable, use reason so that
        # the alert is still handled safely.
        if not alert_key:
            alert_key = reason.lower()

        # ----------------------------------------------------
        # First occurrence
        # ----------------------------------------------------

        if alert_key not in unique_alerts:

            unique_alerts[alert_key] = {
                "process": alert.get(
                    "process",
                    "Unknown"
                ),
                "reason": reason,
                "severity": severity
            }

            continue

        # ----------------------------------------------------
        # Duplicate occurrence
        #
        # Keep the more serious detection.
        # ----------------------------------------------------

        existing_alert = unique_alerts[alert_key]

        existing_severity = str(
            existing_alert.get(
                "severity",
                "INFO"
            )
        ).upper()

        existing_score = SEVERITY_PRIORITY.get(
            existing_severity,
            0
        )

        new_score = SEVERITY_PRIORITY.get(
            severity,
            0
        )

        if new_score > existing_score:

            unique_alerts[alert_key] = {
                "process": alert.get(
                    "process",
                    "Unknown"
                ),
                "reason": reason,
                "severity": severity
            }

        elif new_score == existing_score:

            # If both have the same severity, prefer the
            # more specific detection reason when possible.
            if reason and reason != existing_alert.get(
                "reason",
                ""
            ):

                existing_reason = existing_alert.get(
                    "reason",
                    ""
                )

                if len(reason) > len(existing_reason):

                    unique_alerts[alert_key] = {
                        "process": alert.get(
                            "process",
                            "Unknown"
                        ),
                        "reason": reason,
                        "severity": severity
                    }

    return list(
        unique_alerts.values()
    )


# ============================================================
# CLOUD EVENT SENDER
# ============================================================

def send_event_to_cloud(
    event_type,
    message,
    severity="INFO",
    process=None,
    risk_score=0,
    timestamp=None
):
    """
    Send a SentinelX event to the Render cloud API.

    Local storage remains independent from cloud storage.
    If cloud ingestion fails, SentinelX continues running.
    """

    if not CLOUD_INGEST_KEY:

        print(
            "Cloud ingestion skipped: "
            "INGEST_API_KEY is not configured."
        )

        return False

    if timestamp is None:

        timestamp = datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )

    event_data = {
        "timestamp": timestamp,
        "event_type": event_type,
        "severity": severity,
        "process": process or "",
        "message": message,
        "risk_score": int(risk_score)
    }

    try:

        request_data = json.dumps(
            event_data
        ).encode("utf-8")

        request = Request(
            CLOUD_INGEST_URL,
            data=request_data,
            headers={
                "Content-Type": "application/json",
                "X-SentinelX-Key": CLOUD_INGEST_KEY
            },
            method="POST"
        )

        with urlopen(
            request,
            timeout=15
        ) as response:

            response.read()

            if response.status in (200, 201):

                print(
                    "Cloud event uploaded successfully."
                )

                return True

            print(
                f"Cloud ingestion returned HTTP "
                f"{response.status}"
            )

            return False

    except HTTPError as error:

        print(
            f"Cloud ingestion HTTP error: "
            f"{error.code} {error.reason}"
        )

        return False

    except URLError as error:

        print(
            f"Cloud ingestion connection error: "
            f"{error.reason}"
        )

        return False

    except Exception as error:

        print(
            f"Cloud ingestion error: {error}"
        )

        return False


# ============================================================
# WINDOWS SYSTEM SNAPSHOT
# ============================================================

def collect_system_snapshot():
    """
    Collect system information from the Windows machine
    running SentinelX.
    """

    try:

        hostname = socket.gethostname()

    except Exception:

        hostname = "Unknown"

    # --------------------------------------------------------
    # SentinelX dashboard display name
    #
    # This does NOT change the actual Windows account.
    # --------------------------------------------------------

    try:

        username = "Suraj Baliarsingh"

    except Exception:

        username = os.environ.get(
            "USERNAME",
            "Unknown"
        )

    try:

        operating_system = platform.system()

    except Exception:

        operating_system = "Unknown"

    try:

        os_version = platform.version()

    except Exception:

        os_version = "Unknown"

    return {
        "hostname": hostname,
        "operating_system": operating_system,
        "os_version": os_version,
        "username": username
    }


# ============================================================
# CLOUD SNAPSHOT SENDER
# ============================================================

def send_monitoring_snapshot(
    system_snapshot,
    processes,
    network_connections,
    risk_score
):
    """
    Upload the latest Windows monitoring snapshot.

    Snapshot contains:

        - Windows system information
        - running processes
        - network connections
        - current risk score
        - timestamp
    """

    if not CLOUD_INGEST_KEY:

        print(
            "Cloud snapshot skipped: "
            "INGEST_API_KEY is not configured."
        )

        return False

    timestamp = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    snapshot_data = {
        "timestamp": timestamp,
        "system": system_snapshot,
        "processes": processes,
        "network": network_connections,
        "risk_score": int(risk_score)
    }

    try:

        request_data = json.dumps(
            snapshot_data
        ).encode("utf-8")

        request = Request(
            CLOUD_SNAPSHOT_URL,
            data=request_data,
            headers={
                "Content-Type": "application/json",
                "X-SentinelX-Key": CLOUD_INGEST_KEY
            },
            method="POST"
        )

        with urlopen(
            request,
            timeout=20
        ) as response:

            response.read()

            if response.status in (200, 201):

                print(
                    "Windows monitoring snapshot "
                    "uploaded successfully."
                )

                return True

            print(
                f"Cloud snapshot returned HTTP "
                f"{response.status}"
            )

            return False

    except HTTPError as error:

        print(
            f"Cloud snapshot HTTP error: "
            f"{error.code} {error.reason}"
        )

        return False

    except URLError as error:

        print(
            f"Cloud snapshot connection error: "
            f"{error.reason}"
        )

        return False

    except Exception as error:

        print(
            f"Cloud snapshot error: {error}"
        )

        return False


# ============================================================
# SAVE LOCAL + CLOUD EVENT
# ============================================================

def save_and_sync_event(
    event_type,
    message,
    severity="INFO",
    process=None,
    risk_score=0
):
    """
    Save an event locally and then attempt cloud ingestion.

    Local storage is never dependent on cloud availability.
    """

    timestamp = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    # --------------------------------------------------------
    # LOCAL STORAGE
    # --------------------------------------------------------

    local_saved = save_event(
        event_type=event_type,
        message=message,
        severity=severity,
        process=process,
        risk_score=risk_score,
        timestamp=timestamp
    )

    # --------------------------------------------------------
    # CLOUD STORAGE
    # --------------------------------------------------------

    cloud_saved = send_event_to_cloud(
        event_type=event_type,
        message=message,
        severity=severity,
        process=process,
        risk_score=risk_score,
        timestamp=timestamp
    )

    return local_saved, cloud_saved


# ============================================================
# BANNER
# ============================================================

def show_banner():

    print("================================")
    print("          SENTINELX")
    print(" Cybersecurity Monitoring System")
    print("================================")


# ============================================================
# MONITORING CYCLE
# ============================================================

def monitoring_cycle():

    print(
        "\n========== MONITORING CYCLE =========="
    )

    # --------------------------------------------
    # START MONITORING CYCLE
    # --------------------------------------------

    log_event(
        "SYSTEM",
        "Monitoring cycle started",
        "INFO"
    )

    # --------------------------------------------
    # SYSTEM STATUS
    # --------------------------------------------

    display_system_status()

    # Collect actual Windows system information
    system_snapshot = collect_system_snapshot()

    # --------------------------------------------
    # PROCESS MONITORING
    # --------------------------------------------

    print(
        "Collecting running processes..."
    )

    raw_processes = get_running_processes()
    process_list = get_process_list()

    print(
        "Analyzing processes..."
    )

    # --------------------------------------------
    # BASIC PROCESS DETECTION
    # --------------------------------------------

    alerts = analyze_processes(
        raw_processes
    )

    # --------------------------------------------
    # PROCESS METADATA ANALYSIS
    # --------------------------------------------

    metadata_processes = {
        "powershell.exe",
        "wscript.exe",
        "cscript.exe",
        "mshta.exe",
        "regsvr32.exe",
        "rundll32.exe"
    }

    for process in process_list:

        process_name = process[
            "name"
        ].lower()

        if process_name in metadata_processes:

            try:

                metadata = get_process_details(
                    process["pid"]
                )

                metadata_alerts = (
                    analyze_process_metadata(
                        metadata
                    )
                )

                alerts.extend(
                    metadata_alerts
                )

            except Exception as error:

                print(
                    f"Metadata analysis failed for "
                    f"{process_name} "
                    f"(PID {process['pid']}): "
                    f"{error}"
                )

                log_event(
                    "SYSTEM",
                    (
                        f"Metadata analysis failed for "
                        f"{process_name} "
                        f"(PID {process['pid']})"
                    ),
                    "INFO"
                )

    # --------------------------------------------
    # DUPLICATE ALERT CORRELATION
    # --------------------------------------------

    original_alert_count = len(
        alerts
    )

    alerts = deduplicate_alerts(
        alerts
    )

    deduplicated_alert_count = len(
        alerts
    )

    removed_alert_count = (
        original_alert_count
        - deduplicated_alert_count
    )

    if removed_alert_count > 0:

        print(
            f"Alert correlation removed "
            f"{removed_alert_count} "
            f"duplicate detection(s)."
        )

        log_event(
            "SYSTEM",
            (
                f"Alert correlation removed "
                f"{removed_alert_count} "
                f"duplicate detection(s)"
            ),
            "INFO"
        )

    # --------------------------------------------
    # SECURITY ANALYSIS DISPLAY
    # --------------------------------------------

    display_alerts(
        alerts
    )

    # --------------------------------------------
    # SAVE SECURITY ALERTS
    # --------------------------------------------

    for alert in alerts:

        message = (
            f"{alert['process']} - "
            f"{alert['reason']}"
        )

        log_event(
            "SECURITY_ALERT",
            message,
            alert["severity"]
        )

        alert_risk_score = calculate_risk_score(
            [alert]
        )

        save_and_sync_event(
            event_type="SECURITY_ALERT",
            message=message,
            severity=alert["severity"],
            process=alert["process"],
            risk_score=alert_risk_score
        )

    # --------------------------------------------
    # OVERALL RISK ASSESSMENT
    # --------------------------------------------

    risk_score = calculate_risk_score(
        alerts
    )

    display_risk_score(
        risk_score
    )

    log_event(
        "RISK_ASSESSMENT",
        f"Risk score: {risk_score}/100",
        "INFO"
    )

    save_and_sync_event(
        event_type="RISK_ASSESSMENT",
        message=f"Risk score: {risk_score}/100",
        severity="INFO",
        risk_score=risk_score
    )

    # --------------------------------------------
    # NETWORK MONITORING
    # --------------------------------------------

    print(
        "Collecting network connections..."
    )

    connections = get_network_connections()

    connection_count = len(
        [
            line
            for line in connections.splitlines()
            if line.strip()
        ]
    )

    print(
        f"Network records collected: "
        f"{connection_count}"
    )

    log_event(
        "NETWORK",
        (
            f"{connection_count} "
            f"network records collected"
        ),
        "INFO"
    )

    save_and_sync_event(
        event_type="NETWORK",
        message=(
            f"{connection_count} "
            f"network records collected"
        ),
        severity="INFO",
        risk_score=risk_score
    )

    # --------------------------------------------
    # WINDOWS SNAPSHOT
    # --------------------------------------------

    print(
        "Preparing Windows monitoring snapshot..."
    )

    try:

        snapshot_result = send_monitoring_snapshot(
            system_snapshot=system_snapshot,
            processes=process_list,
            network_connections=connections,
            risk_score=risk_score
        )

        if snapshot_result:

            print(
                "Windows snapshot synchronization: SUCCESS"
            )

        else:

            print(
                "Windows snapshot synchronization: FAILED"
            )

    except Exception as error:

        print(
            f"Windows snapshot synchronization "
            f"error: {error}"
        )

    # --------------------------------------------
    # CYCLE COMPLETE
    # --------------------------------------------

    log_event(
        "SYSTEM",
        "Monitoring cycle completed",
        "INFO"
    )

    print(
        "======================================="
    )


# ============================================================
# MAIN
# ============================================================

def main():

    print(
        "Starting SentinelX...\n"
    )

    show_banner()

    # --------------------------------------------
    # DATABASE INITIALIZATION
    # --------------------------------------------

    initialize_database()

    # --------------------------------------------
    # CLOUD STATUS
    # --------------------------------------------

    if CLOUD_INGEST_KEY:

        print(
            "Cloud ingestion: ENABLED"
        )

        print(
            f"Cloud API: {CLOUD_INGEST_URL}"
        )

        print(
            f"Snapshot API: {CLOUD_SNAPSHOT_URL}"
        )

    else:

        print(
            "Cloud ingestion: DISABLED"
        )

        print(
            "Set INGEST_API_KEY to enable "
            "cloud upload."
        )

    # --------------------------------------------
    # START LOGGING
    # --------------------------------------------

    log_event(
        "SYSTEM",
        "SentinelX continuous monitoring started",
        "INFO"
    )

    # --------------------------------------------
    # CONTINUOUS MONITORING
    # --------------------------------------------

    try:

        while True:

            monitoring_cycle()

            print(
                "\nNext monitoring cycle in "
                "30 seconds..."
            )

            print(
                "Press Ctrl+C to stop SentinelX."
            )

            time.sleep(30)

    except KeyboardInterrupt:

        print(
            "\nSentinelX stopped by user."
        )

        log_event(
            "SYSTEM",
            "SentinelX stopped by user",
            "INFO"
        )

        save_and_sync_event(
            event_type="SYSTEM",
            message="SentinelX stopped by user",
            severity="INFO",
            risk_score=0
        )


# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()